const portfolio = {
  name: "Aman Sharma",
  title: "Blockchain & Full Stack Engineer",
  bio: "Building on-chain apps that scale.",
  github: "https://github.com/AmanSharma7799",
  X: "https://x.com/amansharma7799",
  projects: [
    {
      name: "Universal Ledger (Google Cloud)",
      link: "https://universal-ledger-frontend.vercel.app",
      desc: "A simplified, blockchain-inspired tamper-evident ledger system, modeled after Google Cloud Universal Ledger. This backend application allows you to append entries, verify integrity, and audit logs using SHA256-based hash chaining — without needing a full blockchain.",
      platform: "vercel",
    },
    {
      name: "DEX (Decentralized Exchange)",
      link: "https://github.com/AmanSharma7799/dex",
      desc: "This project implements a Decentralized Exchange (DEX) built using Forge for smart contract development and RabbitMQ for event handling.",
      platform: "github",
    },
    {
      name: "Flashloan Cross-Exchange",
      link: "https://github.com/AmanSharma7799/flashloan-cross-exchange",
      desc: "Arbitrage bot using flash loans across DEXs(Uniswap & SushiSwap)",
      platform: "github",
    },
    {
      name: "NFT Minting",
      link: "https://nft-minting-bay.vercel.app",
      desc: "NFT Minting Decentralized Application (DApp) built with React and Ethers.js v6. It connects to the already deployed ERC-721 smart contract on the Sepolia testnet, allowing users to mint NFTs by providing a metadata URL.",
      platform: "vercel",
    },
  ],
  skills: [
    "Solidity",
    "Foundry",
    "Hardhat",
    "Java",
    "Springboot",
    "Hibernate",
    "Javascript",
    "React.js",
    "Node.js",
    "Express.js",
    "Next.js",
    "AWS",
    "Azure Devops",
    "MySQL",
    "MongoDB",
    "GitHub Actions",
  ],
  contact: "+91 8856044490",
  email: "aman02468@gmail.com",
};
