const portfolio = {
  name: "Aman Sharma",
  title: "Blockchain & Full Stack Engineer",
  bio: "Building on-chain apps that scale.",
  github: "https://github.com/AmanSharma7799",
  X: "https://x.com/amansharma7799",
  projects: [
    {
      name: "Universal Ledger (Google Cloud)",
      link: "https://universal-ledger-frontend.vercel.app",
      desc: "A simplified, blockchain-inspired tamper-evident ledger system, modeled after Google Cloud Universal Ledger. This backend application allows you to append entries, verify integrity, and audit logs using SHA256-based hash chaining — without needing a full blockchain.",
      platform: "vercel",
    },
    {
      name: "DEX (Decentralized Exchange)",
      link: "https://github.com/AmanSharma7799/dex",
      desc: "This project implements a Decentralized Exchange (DEX) built using Forge for smart contract development and RabbitMQ for event handling.",
      platform: "github",
    },
    {
      name: "Flashloan Cross-Exchange",
      link: "https://github.com/AmanSharma7799/flashloan-cross-exchange",
      desc: "Arbitrage bot using flash loans across DEXs(Uniswap & SushiSwap)",
      platform: "github",
    },
    {
      name: "NFT Minting",
      link: "https://nft-minting-bay.vercel.app",
      desc: "NFT Minting Decentralized Application (DApp) built with React and Ethers.js v6. It connects to the already deployed ERC-721 smart contract on the Sepolia testnet, allowing users to mint NFTs by providing a metadata URL.",
      platform: "vercel",
    },
  ],
  skills: [
    "Solidity",
    "Foundry",
    "Hardhat",
    "Java",
    "Springboot",
    "Hibernate",
    "Javascript",
    "React.js",
    "Node.js",
    "Express.js",
    "Next.js",
    "AWS",
    "Azure Devops",
    "Dockers",
    "MySQL",
    "MongoDB",
    "GitHub Actions",
  ],
  contact: "+91 8856044490",
  email: "aman02468@gmail.com",
  experience: [
    {
      company: "Deloitte",
      title: "Consultant",
      duration: "September 2023 – Present",
      logo: "assets/Deloitte-Emblem.png",
      responsibilities: [
        " Engineered contracts to efficiently manage liquidity pools for decentralized exchanges (DEXs), boosting capital efficiency by 20%",
        " Designed and deployed robust Solidity contracts to handle token swaps on decentralized exchanges, increasing transaction volume by 25%",
        " Built cross-chain interoperability into smart contracts, facilitating seamless blockchain network interactions",
        " Developed complex algorithms for smart contracts, successfully reducing gas fees by 15% while maintaining functionality",
      ],
    },
    {
      company: "Stepstrong Software",
      title: "Senior Software Engineer",
      duration: "April 2020 – August 2023",
      logo: "assets/stepstrong.png",
      responsibilities: [
        " Developed Solidity-based solutions to track and verify the ownership of non-fungible tokens (NFTs), ensuring 99.9% accurate tracking.",
        " Integrated smart contracts with Hardware Wallets, strengthening transactions security & reducing fraud risk by 35%.",
        " Architected decentralized loan contracts, Processing over $2M in secure peer-to-peer lending with zero security breaches.",
        " Integrated CI/CD pipelines using GitHub Actions and Docker",
        " Implemented Scalable Microservices Using SpringBoot, improving System Uptime by 35% for an Insurance Platform.",
      ],
    },
  ],
};
